<?php
// $Id: uc_dibsflex.module,v 1.0.0.14 2011/07/21 15:34:12 dibs Exp $

/**
 * @file
 * Integrates DIBS Payment Service
 */

require_once dirname(__FILE__) . '/dibsflex_api/dibsflex_helpers_cms.php';
require_once dirname(__FILE__) . '/dibsflex_api/dibsflex_helpers.php';
require_once dirname(__FILE__) . '/dibsflex_api/dibsflex_api.php';

function getDibsFlexObj() {
    return new dibsflex_api();
}

/**
 * Implementation of hook_menu().
 */

function uc_dibsflex_menu() {
    $items = array();

    $items['cart/dibsflex/success'] = array(
        'title' => 'Order complete',
        'page callback' => 'uc_dibsflex_success',
        'access callback' => 'uc_dibsflex_completion_access',
        'type' => MENU_CALLBACK,
        'file' => 'uc_dibsflex.pages.inc',
    );

    $items['cart/dibsflex/cancel'] = array(
        'title' => 'Order canceled',
        'page callback' => 'uc_dibsflex_cancel',
        'access callback' => 'uc_dibsflex_completion_access',
        'type' => MENU_CALLBACK,
        'file' => 'uc_dibsflex.pages.inc',
    );
    
    $items['cart/dibsflex/redirect'] = array(
        'title' => 'You will be redirected to DIBS in a few seconds...',
        'page callback' => 'uc_dibsflex_redirect',
        'access callback' => 'uc_dibsflex_completion_access',
        'type' => MENU_CALLBACK,
        'file' => 'uc_dibsflex.pages.inc',
    );

    $items['cart/dibsflex/cgiapi'] = array(
        'title' => 'CGI API Request',
        'page callback' => 'uc_dibsflex_cgiapi',
        'type' => MENU_CALLBACK,
        'access callback' => 'uc_dibsflex_admin_access',
    );
    
    $items['cart/dibsflex/callback'] = array(
        'title' => 'Order complete',
        'page callback' => 'uc_dibsflex_callback',
        'access callback' => 'uc_dibsflex_completion_access',
        'type' => MENU_CALLBACK,
        'file' => 'uc_dibsflex.pages.inc',
    );
    
    return $items;
}
    
 /**
  * Implementation of hook_init().
  */
function uc_dibsflex_init() {
    global $conf;
    $conf['i18n_variables'][] = 'uc_dibsflex_method_title';
    $conf['i18n_variables'][] = 'uc_dibsflex_checkout_button';
}
    
/**
 * Make sure anyone can complete their dibs orders.
 */
function uc_dibsflex_completion_access() {
    return TRUE;
}

function uc_dibsflex_admin_access() {
    global $user;

    // Check to see if $user has the administrator role.
    if (user_access('administer')) {
        return TRUE;
    }
    return FALSE;
}

function uc_dibsflex_cgiapi() {
    getDibsFlexObj()->dibsflex_api_cgiapi();
}

/**
 * Implementation of hook_ucga_display().
 */
function uc_dibsflex_ucga_display() {
    // For UC Google Analytics
    if (arg(0) == 'cart' && arg(1) == 'dibsflex' && arg(2) == 'success') {
        return TRUE;
    }
}

/**
 * Implementation of hook_form_alter().
 */
function uc_dibsflex_form_alter(&$form, $form_state, $form_id) {
    if ($form_id == 'uc_cart_checkout_review_form' && ($order_id = intval($_SESSION['cart_order'])) > 0) {
        $order = uc_order_load($order_id);

        if ($order->payment_method == 'dibsflex') {
            drupal_add_css(drupal_get_path('module', 'uc_dibsflex') .'/uc_dibsflex.css');
            unset($form['submit']);
            $form['#prefix'] = '<table id="dibsflex-tab"><tr><td>';
            $form['#suffix'] = '</td><td>'. drupal_get_form('uc_dibsflex_form', $order) .'</td></tr></table>';
        }
    }
}

/**
 * Implementation of hook_payment_method().
 *
 * @see uc_payment_method_dibs()
 */
function uc_dibsflex_payment_method() {
    $path = base_path() . drupal_get_path('module', 'uc_dibsflex');
    $title = variable_get('uc_dibsflex_method_title', t('DIBS | Secure Payment Services'));
    $title .= '<br /><img src="'. $path .'/uc_dibsflex.gif" style="position: relative; left: 2.5em;" />';

    $methods[] = array(
        'id' => 'dibsflex',
        'name' => t('DIBS FlexWin'),
        'title' => $title,
        'review' => t('DIBS FlexWin Payment'),
        'desc' => t('You will be redirected to DIBS in a few seconds...'),
        'callback' => 'uc_payment_method_dibsflex',
        'weight' => 1,
        'checkout' => TRUE,
        'no_gateway' => TRUE,
    );
    
    return $methods;
}


/**
 * Add DIBS settings to the payment method settings form.
 *
 * @see uc_dibsflex_payment_method()
 */
function uc_payment_method_dibsflex($op, &$arg1) {
    switch ($op) {
    // Settings page //
        case 'settings':
            
            $form['uc_dibsflex_method_title'] = array(
                '#type' => 'textfield',
                '#title' => t('Title'),
                '#description' => t('Payment method name displayed for customers. Ex: DibsGW'),
                '#default_value' => variable_get('uc_dibsflex_method_title', t('DIBS FlexWin | Secure Payment Services')),
            );
            
            $form['uc_dibsflex_mid'] = array(
                '#type' => 'textfield',
                '#title' => t('DIBS Merchant ID'),
                '#description' => t('Your dibs merchant account number.'),
                '#default_value' => variable_get('uc_dibsflex_mid', ''),
                '#size' => 16,
            );
            
            $form['uc_dibsflex_apiuser'] = array(
                '#type' => 'textfield',
                '#title' => t('DIBS API username'),
                '#description' => t('Your dibs account api user.'),
                '#default_value' => variable_get('uc_dibsflex_apiuser', ''),
                '#size' => 16,
            );
                        
            $form['uc_dibsflex_apipass'] = array(
                '#type' => 'textfield',
                '#title' => t('DIBS API password'),
                '#description' => t('Your dibs account api password.'),
                '#default_value' => variable_get('uc_dibsflex_apipass', ''),
                '#size' => 16,
            );
            
            $form['uc_dibsflex_curr'] = array(
                '#type' => 'select',
                '#title' => t('Currency'),
                '#options' => array_flip(getDibsFlexObj()->dibsflex_api_getCurrencyArray()),
                '#default_value' => variable_get('uc_dibsflex_curr', '840'),
            );
      
            $form['uc_dibsflex_testmode'] = array(
                '#type' => 'checkbox',
                '#title' => t('Enable test mode.'),
                '#return_value' => 'yes',
                '#default_value' => variable_get('uc_dibsflex_testmode', TRUE),
            );
      
            $form['uc_dibsflex_uniq'] = array(
                '#type' => 'checkbox',
                '#title' => t('Unique order id'),
                '#return_value' => 'yes',
                '#default_value' => variable_get('uc_dibsflex_uniq', FALSE),
            );
            
            $form['uc_dibsflex_paytype'] = array(
                '#type' => 'textfield',
                '#title' => t('Paytype'),
                '#default_value' => variable_get('uc_dibsflex_paytype', 'VISA,MC'),
                '#size' => 16,
            );
      
            $form['uc_dibsflex_lang'] = array(
                '#type' => 'select',
                '#title' => t('Language FlexWin'),
                '#description' => t('Adjust language for FlexWin.'),
                '#options' => array(
                    'da' => t('Danish'),
                    'nl' => t('Dutch'),
                    'en' => t('English'),
                    'fo' => t('Faroese'),
                    'fi' => t('Finnish'),
                    'fr' => t('French'),
                    'de' => t('German'),
                    'it' => t('Italian'),
                    'no' => t('Norwegian'),
                    'pl' => t('Polish'),
                    'es' => t('Spanish'),
                    'sv' => t('Swedish'),
                ),
                '#default_value' => variable_get('uc_dibsflex_lang', 'en'),
            );
            
            $form['uc_dibsflex_md51'] = array(
                '#type' => 'textfield',
                '#title' => t('MD5 Key 1'),
                '#description' => t('Transaction protection for FlexWin.'),
                '#default_value' => variable_get('uc_dibsflex_md51', ''),
            );
            
            $form['uc_dibsflex_md52'] = array(
                '#type' => 'textfield',
                '#title' => t('MD5 Key 2'),
                '#description' => t('Transaction protection for FlexWin.'),
                '#default_value' => variable_get('uc_dibsflex_md52', ''),
            );
            
            $form['uc_dibsflex_fee'] = array(
                '#type' => 'checkbox',
                '#title' => t('Add fee'),
                '#return_value' => 'yes',
                '#description' => t('Add fee to Standart Payment Window and FlexWin amounts.'),
                '#default_value' => variable_get('uc_dibsflex_fee', FALSE),
            );
            
            $form['uc_dibsflex_voucher'] = array(
                '#type' => 'checkbox',
                '#title' => t('Vouchers'),
                '#return_value' => 'yes',
                '#description' => t('Allow to customers use vouchers on checkout.'),
                '#default_value' => variable_get('uc_dibsflex_voucher', FALSE),
            );
      
            $form['uc_dibsflex_capt'] = array(
                '#type' => 'checkbox',
                '#title' => t('Capture Now'),
                '#return_value' => 'yes',
                '#description' => t('Only used if FlexWin is selected.'),
                '#default_value' => variable_get('uc_dibsflex_capt', FALSE),
            );
        
            $form['uc_dibsflex_skiplast'] = array(
                '#type' => 'checkbox',
                '#title' => t('Skip last page'),
                '#return_value' => 'yes',
                '#description' => t('Only used if FlexWin is selected.'),
                '#default_value' => variable_get('uc_dibsflex_skiplast', FALSE),
            );
            
            $form['uc_dibsflex_account'] = array(
                '#type' => 'textfield',
                '#title' => t('Account'),
                '#description' => t('Only used if FlexWin is selected.'),
                '#default_value' => variable_get('uc_dibsflex_account', ''),
            );
            
            $form['uc_dibsflex_decor'] = array(
                '#type' => 'select',
                '#title' => t('FlexWin Decorator'),
                '#description' => t('Adjust language for FlexWin.'),
                '#options' => array(
                    'default' => t('Default'),
                    'basal' => t('Basal'),
                    'reach' => t('Rich'),
                    'own' => t('Own Decorator'),
                ),
                '#default_value' => variable_get('uc_dibsflex_decor', 'default'),
            );
        
            $form['uc_dibsflex_color'] = array(
                '#type' => 'select',
                '#title' => t('FlexWin Color'),
                '#description' => t('Adjust color for FlexWin.'),
                '#options' => array(
                    'blank' => t('None'),
                    'sand' => t('Sand'),
                    'grey' => t('Grey'),
                    'blue' => t('Blue'),
                ),
                '#default_value' => variable_get('uc_dibsflex_color', 'blank'),
            );
      
            $form['uc_dibsflex_distr'] = array(
                '#type' => 'select',
                '#title' => t('Distribution method'),
                '#description' => t('Only relevant for PayByBill payment type.'),
                '#options' => array(
                    'empty' => t('-'),
                    'paper' => t('Paper'),
                    'email' => t('Email'),
                ),
                '#default_value' => variable_get('uc_dibsflex_distr', 'empty'),
            );
      
            return $form;
      break;
    }
}

function uc_dibsflex_order_pane() {
    $panes[] = array(
        'id' => 'dibscontrols',
        'callback' => 'uc_dibsflex_cgi_buttons',
        'title' => t('DIBS controls'),
        'desc' => t('Specify and collect payment for an order.'),
        'class' => 'pos-left',
        'weight' => 4,
        'show' => array('view'),
    );
    return $panes;
}

function uc_dibsflex_cgi_buttons($op, $oOrder) {
    $sOutput = "";
    switch ($op) {
        case 'view':
            if($oOrder->payment_method == 'dibsflex') {
                $sOutput = getDibsFlexObj()->dibsflex_api_cgiButtons($oOrder->order_id);
            }
        break;
    }
    return $sOutput;
}

function uc_dibsflex_form($form_state, $order) {
    // adding separate tax rates for each product
    getDibsFlexObj()->uc_dibsflex_recalculate_tax($order);

    $aData = getDibsFlexObj()->dibsflex_api_requestModel($order);

    $form['#action'] = url('cart/dibsflex/redirect', array('absolute' => TRUE));

    foreach ($aData as $name => $value) {
        $form[$name] = array('#type' => 'hidden', '#value' => $value);
    }

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit Order'),
    );

    return $form;
}
?>